"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
type Article={id?:string;title:string;slug:string;excerpt:string;content:string;category:string;tags:string;coverImage:string;status:string};
export function ArticleEditor({mode,article}:{mode:"create"|"edit";article?:Article}) {
 const router=useRouter();const [form,setForm]=useState<Article>(article??{title:"",slug:"",excerpt:"",content:"",category:"Mathematics",tags:"",coverImage:"",status:"DRAFT"});const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 function update(key:keyof Article,value:string){setForm(old=>({...old,[key]:value}));}
 async function save(status:"DRAFT"|"PUBLISHED"){setBusy(true);setError("");try{const url=mode==="create"?"/api/admin/articles":`/api/admin/articles/${form.id}`;const res=await fetch(url,{method:mode==="create"?"POST":"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...form,status,tags:form.tags.split(",").map(t=>t.trim()).filter(Boolean)})});const data=await res.json() as {error?:string;id?:string};if(!res.ok)throw new Error(data.error??"Unable to save article.");if(mode==="create")router.replace(`/admin/articles/${data.id}`);else router.refresh();setForm(old=>({...old,id:data.id??old.id,status}));}catch(e){setError(e instanceof Error?e.message:"Save failed.");}finally{setBusy(false);}}
 function submit(e:FormEvent){e.preventDefault();void save("DRAFT");}
 return <><header className="editor-top"><Link href="/admin">← Dashboard</Link><span>MICROMATH / EDITOR</span><div><button type="button" className="secondary-button" disabled={busy} onClick={()=>void save("DRAFT")}>Save draft</button><button type="button" disabled={busy} onClick={()=>void save("PUBLISHED")}>{busy?"Saving…":"Publish ↗"}</button></div></header><form className="editor-form" onSubmit={submit}><div className="eyebrow">ARTICLE {mode==="create"?"COMPOSITION":"EDITING"}</div><input className="title-input" placeholder="Article title" required maxLength={180} value={form.title} onChange={e=>update("title",e.target.value)}/><input placeholder="url-slug (optional; generated from title)" value={form.slug} onChange={e=>update("slug",e.target.value)}/><textarea className="excerpt-input" placeholder="Short summary / excerpt" required maxLength={320} value={form.excerpt} onChange={e=>update("excerpt",e.target.value)}/><div className="editor-fields"><label>Category<input required value={form.category} onChange={e=>update("category",e.target.value)}/></label><label>Tags (comma separated)<input value={form.tags} onChange={e=>update("tags",e.target.value)}/></label></div><label>Cover image URL<input type="url" placeholder="https://…" value={form.coverImage} onChange={e=>update("coverImage",e.target.value)}/></label><label>Article body <span className="field-hint">Plain text with paragraph breaks</span><textarea className="content-input" required value={form.content} onChange={e=>update("content",e.target.value)} placeholder="Begin writing your article…"/></label>{error?<p className="form-error" role="alert">{error}</p>:null}<div className="editor-bottom"><span>Current status: {form.status}</span><button type="submit" className="secondary-button" disabled={busy}>Save as draft</button><button type="button" disabled={busy} onClick={()=>void save("PUBLISHED")}>Publish article ↗</button></div></form></>;
}